install.packages("jsonlite")
library(jsonlite)
x1 <- fromJSON("Data/StreamingHistory0.json")
x1 <- data.frame(x1)
x2 <- fromJSON("Data/StreamingHistory1.json")
x2 <- data.frame(x2)
x3 <- fromJSON("Data/StreamingHistory2.json")
x3 <- data.frame(x3)
streams <- rbind(x1,x2,x3)
View(streams)
library <- fromJSON("Data/YourLibrary.json", flatten=TRUE)
View(library)
str(library)
lib.tracks <- data.frame(library$tracks)
lib.albums <- data.frame(library$albums)
lib.artists <- data.frame(library$artists)
playlist <- fromJSON("Data/Playlist1.json")
playlists <- playlist$playlists
